### PR TITLE
CartoDB Provider

### PR DESCRIPTION
**Pull request by timwis**
The work was done by @chriswhong and @talos, I just patched their changes to accommodate #149

### CODE REVIEW

**Comment by timwis** [comment]
Fixed offset, export, record count, and full text search. Should be ready to merge, just wanna test how choropleth map would work.

**Comment by timwis** [comment]
Okay I could use some advice on this one. The way vizwit is designed to work is: the dataset is meant to have a column relating to the boundary, ie. "police district objectid." In socrata, these columns are added magically when you create datalens pages (denormalised onto the dataset as system fields). Theoretically, if you had something simpler like CKAN datastore you could compute these yourself and add them to the dataset. So vizwit does a query like `SELECT boundary_id, count(*) FROM dataset GROUP BY boundary_id`, then fetches the geojson and does a join on the `boundary_id`.

Carto _may_ be able to make this simpler, resulting in a single request since it could do the join and return the boundaries geojson, but it would involve a much larger refactor to accommodate that (not to mention that no other datastore will do that, so it'd be a provider-specific map card).

Thoughts? /cc @chriswhong @talos

**Comment by chriswhong** [comment]
If you are doing to join client side it is the same amount of work to get
the nonspatial data from carto and do a 2nd API call to get the geometries.

Carto does allow you to get everything in one call to the API but nothing
else can replicate that so to me it makes sense to just do the join client
side.

-C

**Comment by timwis** [comment]
Progress so far: http://vizwit-cartodb.surge.sh/?gist=39c8e1fd5639db1f752298baf3450fb4

**Pull request merged**
